// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: messenger.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivedId    int64                  `protobuf:"varint,1,opt,name=received_id,json=receivedId,proto3" json:"received_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_messenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetReceivedId() int64 {
	if x != nil {
		return x.ReceivedId
	}
	return 0
}

func (x *SendMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_messenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{1}
}

type CheckChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckChatsRequest) Reset() {
	*x = CheckChatsRequest{}
	mi := &file_messenger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChatsRequest) ProtoMessage() {}

func (x *CheckChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChatsRequest.ProtoReflect.Descriptor instead.
func (*CheckChatsRequest) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{2}
}

func (x *CheckChatsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*NewMessage          `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckChatsResponse) Reset() {
	*x = CheckChatsResponse{}
	mi := &file_messenger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChatsResponse) ProtoMessage() {}

func (x *CheckChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChatsResponse.ProtoReflect.Descriptor instead.
func (*CheckChatsResponse) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{3}
}

func (x *CheckChatsResponse) GetMessages() []*NewMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type NewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	SenderId      int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceivedId    int64                  `protobuf:"varint,3,opt,name=received_id,json=receivedId,proto3" json:"received_id,omitempty"`
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessage) Reset() {
	*x = NewMessage{}
	mi := &file_messenger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessage) ProtoMessage() {}

func (x *NewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessage.ProtoReflect.Descriptor instead.
func (*NewMessage) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{4}
}

func (x *NewMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NewMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *NewMessage) GetReceivedId() int64 {
	if x != nil {
		return x.ReceivedId
	}
	return 0
}

func (x *NewMessage) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

type DelMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelMessageRequest) Reset() {
	*x = DelMessageRequest{}
	mi := &file_messenger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMessageRequest) ProtoMessage() {}

func (x *DelMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMessageRequest.ProtoReflect.Descriptor instead.
func (*DelMessageRequest) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{5}
}

func (x *DelMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DelMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelMessageResponse) Reset() {
	*x = DelMessageResponse{}
	mi := &file_messenger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMessageResponse) ProtoMessage() {}

func (x *DelMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMessageResponse.ProtoReflect.Descriptor instead.
func (*DelMessageResponse) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{6}
}

type SendFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceivedId    int64                  `protobuf:"varint,2,opt,name=received_id,json=receivedId,proto3" json:"received_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	DatabasePath  string                 `protobuf:"bytes,4,opt,name=database_path,json=databasePath,proto3" json:"database_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileRequest) Reset() {
	*x = SendFileRequest{}
	mi := &file_messenger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileRequest) ProtoMessage() {}

func (x *SendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileRequest.ProtoReflect.Descriptor instead.
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{7}
}

func (x *SendFileRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendFileRequest) GetReceivedId() int64 {
	if x != nil {
		return x.ReceivedId
	}
	return 0
}

func (x *SendFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SendFileRequest) GetDatabasePath() string {
	if x != nil {
		return x.DatabasePath
	}
	return ""
}

type SendFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileResponse) Reset() {
	*x = SendFileResponse{}
	mi := &file_messenger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileResponse) ProtoMessage() {}

func (x *SendFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileResponse.ProtoReflect.Descriptor instead.
func (*SendFileResponse) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{8}
}

var File_messenger_proto protoreflect.FileDescriptor

const file_messenger_proto_rawDesc = "" +
	"\n" +
	"\x0fmessenger.proto\x12\tmessenger\x1a\x0ftimestamp.proto\"f\n" +
	"\x12SendMessageRequest\x12\x1f\n" +
	"\vreceived_id\x18\x01 \x01(\x03R\n" +
	"receivedId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x15\n" +
	"\x13SendMessageResponse\",\n" +
	"\x11CheckChatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"G\n" +
	"\x12CheckChatsResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.messenger.NewMessageR\bmessages\"\x97\x01\n" +
	"\n" +
	"NewMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceived_id\x18\x03 \x01(\x03R\n" +
	"receivedId\x127\n" +
	"\tcreate_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt\",\n" +
	"\x11DelMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x14\n" +
	"\x12DelMessageResponse\"\x91\x01\n" +
	"\x0fSendFileRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceived_id\x18\x02 \x01(\x03R\n" +
	"receivedId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12#\n" +
	"\rdatabase_path\x18\x04 \x01(\tR\fdatabasePath\"\x12\n" +
	"\x10SendFileResponse2\xbb\x02\n" +
	"\x10MessengerService\x12L\n" +
	"\vSendMessage\x12\x1d.messenger.SendMessageRequest\x1a\x1e.messenger.SendMessageResponse\x12I\n" +
	"\n" +
	"CheckChats\x12\x1c.messenger.CheckChatsRequest\x1a\x1d.messenger.CheckChatsResponse\x12I\n" +
	"\n" +
	"DelMessage\x12\x1c.messenger.DelMessageRequest\x1a\x1d.messenger.DelMessageResponse\x12C\n" +
	"\bSendFile\x12\x1a.messenger.SendFileRequest\x1a\x1b.messenger.SendFileResponseB\x03Z\x01.b\x06proto3"

var (
	file_messenger_proto_rawDescOnce sync.Once
	file_messenger_proto_rawDescData []byte
)

func file_messenger_proto_rawDescGZIP() []byte {
	file_messenger_proto_rawDescOnce.Do(func() {
		file_messenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messenger_proto_rawDesc), len(file_messenger_proto_rawDesc)))
	})
	return file_messenger_proto_rawDescData
}

var file_messenger_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_messenger_proto_goTypes = []any{
	(*SendMessageRequest)(nil),    // 0: messenger.SendMessageRequest
	(*SendMessageResponse)(nil),   // 1: messenger.SendMessageResponse
	(*CheckChatsRequest)(nil),     // 2: messenger.CheckChatsRequest
	(*CheckChatsResponse)(nil),    // 3: messenger.CheckChatsResponse
	(*NewMessage)(nil),            // 4: messenger.NewMessage
	(*DelMessageRequest)(nil),     // 5: messenger.DelMessageRequest
	(*DelMessageResponse)(nil),    // 6: messenger.DelMessageResponse
	(*SendFileRequest)(nil),       // 7: messenger.SendFileRequest
	(*SendFileResponse)(nil),      // 8: messenger.SendFileResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_messenger_proto_depIdxs = []int32{
	4, // 0: messenger.CheckChatsResponse.messages:type_name -> messenger.NewMessage
	9, // 1: messenger.NewMessage.create_at:type_name -> google.protobuf.Timestamp
	0, // 2: messenger.MessengerService.SendMessage:input_type -> messenger.SendMessageRequest
	2, // 3: messenger.MessengerService.CheckChats:input_type -> messenger.CheckChatsRequest
	5, // 4: messenger.MessengerService.DelMessage:input_type -> messenger.DelMessageRequest
	7, // 5: messenger.MessengerService.SendFile:input_type -> messenger.SendFileRequest
	1, // 6: messenger.MessengerService.SendMessage:output_type -> messenger.SendMessageResponse
	3, // 7: messenger.MessengerService.CheckChats:output_type -> messenger.CheckChatsResponse
	6, // 8: messenger.MessengerService.DelMessage:output_type -> messenger.DelMessageResponse
	8, // 9: messenger.MessengerService.SendFile:output_type -> messenger.SendFileResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_messenger_proto_init() }
func file_messenger_proto_init() {
	if File_messenger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messenger_proto_rawDesc), len(file_messenger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messenger_proto_goTypes,
		DependencyIndexes: file_messenger_proto_depIdxs,
		MessageInfos:      file_messenger_proto_msgTypes,
	}.Build()
	File_messenger_proto = out.File
	file_messenger_proto_goTypes = nil
	file_messenger_proto_depIdxs = nil
}
