syntax = "proto3";

package users;

option go_package = ".";

message TLSRequest {
  string id = 1;
  string client_public_key = 2;
  bool is_registring = 3;
}

message TLSResponse {
  string server_public_key = 1;
}

message RegisterRequest {
  string login = 1;
  string name = 2;
  string password = 3;
  string device = 4;
}

message RegisterResponse {
  string key = 1;
}

message AuthRequest {
  string login = 1;
  string password = 2;
  string device = 3;
}

message AuthResponse {
  string name = 1;
  string key = 2;
}

message GetAuthInfoRequest {
  string device = 1;
}

message GetAuthInfoResponse {
  string key = 1;
  int64 user_id = 2;
}

message SearchRequest {
  string query = 1;
}

message UserInfo {
  string login = 1;
  string name = 2;
  int64 id = 3;
}

message SearchResponse {
  repeated UserInfo users = 1;
}

message GetInfoByIDRequest {
  int64 id = 1;
}

message GetInfoByIDResponse {
  string login = 1;
  string name = 2;
}

service UsersService {
  rpc TLS(TLSRequest) returns (TLSResponse);
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Auth(AuthRequest) returns (AuthResponse);
  rpc GetAuthInfo(GetAuthInfoRequest) returns (GetAuthInfoResponse);
  rpc Search(SearchRequest) returns (SearchResponse);
  rpc GetInfoByID(GetInfoByIDRequest) returns (GetInfoByIDResponse);
}
